### ISSUE TITLE
Timeouts During Import

### ISSUE THREAD

**Issue by homerlex** [eltoroit/ETCopyData#12]
Since installing version 0.4.3 I have had several occasions where the import times out.  Its not always on the same table.  Usually after a couple times retrying the import it goes through.  I've never had this happen with the previous version (maybe just lucky?).

Here is the output from a couple of the timeouts:

```
18:12:45.441Z   73      TRACE   Importer.js:155         [PTDataDestination9] Importing Sobject: [PTPay__PGSettings__c] (1 of 13)
18:14:25.889Z   74      FATAL   Util.js:46              *** Abort Counter: 1 ***
18:14:25.890Z   75      FATAL   Util.js:47              "PollingTimeout: Polling time out. Job Id = 750L0000003vQNWIA2 , batch Id = 751L0000003CzxUIAS\n    at Timeout.poll [as _onTimeout] (C:\\Users\\me\\AppData\\Local\\sfdx\\plugins\\node_modules\\jsforce\\lib\\api\\bulk.js:573:17)\n    at ontimeout (timers.js:475:11)\n    at tryOnTimeout (timers.js:310:5)\n    at Timer.listOnTimeout (timers.js:270:5)"
 !    { Error
 !    at Function.throwError
 !    (C:\Users\me\AppData\Local\sfdx\plugins\node_modules\etcopydata\lib\@ELTOROIT\Util.js:49:15)
 !    at orgDestination.conn.bulk.load
 !    (C:\Users\me\AppData\Local\sfdx\plugins\node_modules\etcopydata\lib\@ELTOROIT\Importer.js:216:41)
 !    at C:\Users\me\AppData\Local\sfdx\plugins\node_modules\jsforce\lib\api\bulk.js:511:9
 !    at _combinedTickCallback (internal/process/next_tick.js:131:7)
 !    at process._tickCallback (internal/process/next_tick.js:180:9)
 !    cause:
 !    { PollingTimeout: Polling time out. Job Id = 750L0000003vQNWIA2 , batch Id = 751L0000003CzxUIAS
 !    at Timeout.poll [as _onTimeout]
 !    (C:\Users\me\AppData\Local\sfdx\plugins\node_modules\jsforce\lib\api\bulk.js:573:17)
 !    at ontimeout (timers.js:475:11)
 !    at tryOnTimeout (timers.js:310:5)
 !    at Timer.listOnTimeout (timers.js:270:5)
 !    name: 'PollingTimeout',
 !    jobId: '750L0000003vQNWIA2',
 !    batchId: '751L0000003CzxUIAS' },
 !    name: 'Error',
 !    actions: null,
 !    exitCode: -1 }
 
 18:16:53.924Z   82      TRACE   Importer.js:155         [PTDataDestination9] Importing Sobject: [PTD__OSettings__c] (4 of 13)
18:18:35.107Z   83      FATAL   Util.js:46              *** Abort Counter: 1 ***
18:18:35.109Z   84      FATAL   Util.js:47              "PollingTimeout: Polling time out. Job Id = 750L0000003vQNqIAM , batch Id = 751L0000003CzxoIAC\n    at Timeout.poll [as _onTimeout] (C:\\Users\\me\\AppData\\Local\\sfdx\\plugins\\node_modules\\jsforce\\lib\\api\\bulk.js:573:17)\n    at ontimeout (timers.js:475:11)\n    at tryOnTimeout (timers.js:310:5)\n    at Timer.listOnTimeout (timers.js:270:5)"
 !    { Error
 !    at Function.throwError
 !    (C:\Users\me\AppData\Local\sfdx\plugins\node_modules\etcopydata\lib\@ELTOROIT\Util.js:49:15)
 !    at orgDestination.conn.bulk.load
 !    (C:\Users\me\AppData\Local\sfdx\plugins\node_modules\etcopydata\lib\@ELTOROIT\Importer.js:216:41)
 !    at C:\Users\me\AppData\Local\sfdx\plugins\node_modules\jsforce\lib\api\bulk.js:511:9
 !    at _combinedTickCallback (internal/process/next_tick.js:131:7)
 !    at process._tickCallback (internal/process/next_tick.js:180:9)
 !    cause:
 !    { PollingTimeout: Polling time out. Job Id = 750L0000003vQNqIAM , batch Id = 751L0000003CzxoIAC
 !    at Timeout.poll [as _onTimeout]
 !    (C:\Users\me\AppData\Local\sfdx\plugins\node_modules\jsforce\lib\api\bulk.js:573:17)
 !    at ontimeout (timers.js:475:11)
 !    at tryOnTimeout (timers.js:310:5)
 !    at Timer.listOnTimeout (timers.js:270:5)
 !    name: 'PollingTimeout',
 !    jobId: '750L0000003vQNqIAM',
 !    batchId: '751L0000003CzxoIAC' },
 !    name: 'Error',
 !    actions: null,
 !    exitCode: -1 }
```

**Comment by eltoroit** [comment]
Maybe you were lucky... Have you tried increasing the timeout limit in the ETCopyData.json file?

**Comment by homerlex** [comment]
I have not tried increasing the timeout.  When it works properly it flies right through.  Why would it sometimes takes a long time?  There is nothing else going on in the destination org at the time I import.

**Comment by eltoroit** [comment]
From the log, I see the issue is inside the Bulk call to Salesforce, not in my code. Not sure what could be going on there.
